name: check

on:
  push:
    branches:
      - "update_flake_lock_action"
jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    name: Run flake checks
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs Inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Run flake checks
        run: |
          nix flake check -L