name: check

on:
  pull_request:
    branches:
      - "update_flake_lock_action"
jobs:
  check:
    name: Run flake checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs Inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Run flake checks
        run: |
          nix flake check -L