name: Update Flake

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - flake.lock

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-flake-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.draft == false &&
      startsWith(github.head_ref, 'dependabot/nix/')
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Flake checks (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nixpkgs Inputs
        uses: DeterminateSystems/flake-checker-action@v10
      - name: Run flake checks
        run: nix flake check -L --accept-flake-config

  merge:
    if: >-
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.draft == false &&
      startsWith(github.head_ref, 'dependabot/nix/')
    runs-on: ubuntu-latest
    name: Merge after checks pass
    needs: checks
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge
        run: gh pr merge "$PR_URL" --delete-branch --squash --match-head-commit "$PR_HEAD_SHA"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_URL: ${{ github.event.pull_request.html_url }}
