name: Update Flake

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '00 5 * * 6' # runs weekly on Saturday at 05:00

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  lockfile:
    name: Lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Add Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      # done with setup, now start updating
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: nix flake update --commit-lock-file
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: update_flake_lock_action
          delete-branch: true
          sign-commits: true
          title: Update flake.lock
      - run: gh pr merge --auto -d
        env:
          GH_TOKEN: ${{ github.token }}
