name: Update Flake

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '00 5 * * 6' # runs weekly on Saturday at 05:00
  push:
    paths:
      - '.github/workflows/update.yml'

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  lockfile:
    name: Update flake.lock
    runs-on: ubuntu-latest
    outputs:
      pr-sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
      pr-url: ${{ steps.cpr.outputs.pull-request-url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Add Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      # done with setup, now start updating
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: nix flake update --commit-lock-file
      - uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          branch: update_flake_lock_action
          delete-branch: true
          sign-commits: true
          title: Update flake.lock
  checks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    name: Flake checks
    runs-on: ${{ matrix.os }}
    needs: lockfile
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.lockfile.outputs.pr-sha }}
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs Inputs
        uses: DeterminateSystems/flake-checker-action@v9
      - name: Run flake checks
        run: |
          nix flake check -L
  merge:
    runs-on: "ubuntu-latest"
    name: "Auto-merge after checks pass"
    needs: [checks, lockfile]
    steps:
      - name: Checkout main branch again
        uses: actions/checkout@v4
      - run: gh pr merge ${{ needs.lockfile.outputs.pr-url }} --auto --delete-branch --squash
        env:
          GH_TOKEN: ${{ github.token }}